version: 1-alpha.1

releases:
  core-design-storybook:
    name: Core-design Storybook
    autodeploy-on: default
    chart: csssr/static-site@~1.0.0
    static-params:
      projectID: core-design-storybook
    builds:
      - workflow: build-storybook.yaml
        values:
          buildID: build-{{ .Build.RunID }}
