version: 1-alpha.1

releases:
  core-design-storybook:
    name: Core-design Storybook
    cluster: gke-csssr-testing
    autodeploy-on: default
    chart: oci://quay.csssr.cloud/charts/static-site@~1.1.6
    slack:
      - CKF42GD36 # #csssr_builds
    static-params:
      projectID: core-design-storybook
      tlsSecret: core-design-storybook-tls
    builds:
      - workflow: build-storybook.yaml
        values:
          buildID: build-{{ .Build.RunID }}
