language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: 'libraries'
      install:
        - yarn install --no-lockfile
      before_script:
        - yarn run version
      script:
        - yarn run build
      deploy:
        - provider: script
          script: 'yarn run release'
          skip_cleanup: true
          on:
            branch: master
      branches:
        only:
          - master
    - stage: 'docs'
      install:
        - npm install --prefix=./packages/core-docs --registry https://registry.npmjs.org/
      script:
        - npm run build --prefix=./packages/core-docs
        - cat './packages/core-docs/node_modules/@asmy/core-design/package.json' | grep version

stages:
  - name: libraries
    if: branch = master
  - name: docs
    if: branch = master
