name: Storybook
on:
  workflow_dispatch:
    inputs:
      kuberta_system:

jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest

    steps:
      - uses: docker://quay.csssr.cloud/csssr/kuberta-init-workflow:v1

      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: core-design

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn install --freeze-lockfile --no-interactive
        working-directory: core-design/packages/core-design

      - run: yarn run build-storybook -o static
        working-directory: core-design/packages/core-design

      - uses: ./actions/upload-static/v1beta1
        with:
          project-id: core-design-storybook
          files: ./core-design/packages/core-design/static
          auth: ${{ secrets.CDN_UPLOAD_SECRET }}
          token: ${{ secrets.GITHUB_TOKEN }}
